import sys
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

from src.config import OUTPUTS_DIR


def format_duration(seconds: int) -> str:
    """Đổi số giây thành định dạng Giờ:Phút:Giây thân thiện."""
    if not seconds:
        return "N/A"
    hrs = seconds // 3600
    mins = (seconds % 3600) // 60
    secs = seconds % 60
    if hrs > 0:
        return f"{hrs}h {mins:02d}m {secs:02d}s"
    return f"{mins}m {secs:02d}s"


def save_markdown_report(
    summary_text: str,
    metadata: Dict[str, Any],
    source_type: str,
) -> Path:
    """Lưu bản tóm tắt thành file Markdown hoàn chỉnh trong outputs/."""
    title = metadata.get("title", "Video_Summary")
    clean_title = re.sub(r'[\\/*?:"<>|]', "", title)
    clean_title = re.sub(r"\s+", "_", clean_title).strip("_")[:60]
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{clean_title}_{timestamp}.md"
    file_path = OUTPUTS_DIR / filename

    header_info = (
        f"<!---\n"
        f"Generated by: Academic YouTube Summarizer\n"
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"Source Type: {source_type.upper()}\n"
        f"URL: {metadata.get('webpage_url')}\n"
        f"-->\n\n"
    )

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(header_info + summary_text.strip() + "\n")

    return file_path
